db:
  build: build/containers/mysql
  container_name: mysql_container
  ports:
   - "3306:3306"
#web:
#  build: build/containers/apache
#  container_name: apache_container
#  ports:
#   - "80:80"
#  links:
#   - db
#  volumes:
#    - /project