db:
  build: build/images/mysql
  container_name: mysql_container
  ports:
   - "3306:3306"
web:
  build: build/images/apache
  container_name: apache_container
  ports:
   - "80:80"
  links:
   - db
  volumes:
    - /var/www/html/project:/var/www/html
